name: End-to-End Tests

on: [push]

jobs:
  e2e:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2

      - name: Cypress Run
        uses: cypress-io/github-action@v1
        with:
          env: TESTS_FIREBASE_DATABASE=${{ secrets.TESTS_FIREBASE_DATABASE }}

          start: npm start
          wait-on: "http://localhost:3000"

          record: true
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          REACT_APP_FIREBASE_URL: ${{ secrets.REACT_APP_FIREBASE_URL }}
          REACT_APP_MAPBOX_API_TOKEN: ${{ secrets.REACT_APP_MAPBOX_API_TOKEN }}
          REACT_APP_UPLOADCARE_KEY: ${{ secrets.REACT_APP_UPLOADCARE_KEY }}
          REACT_APP_GOOGLE_STATIC_KEY: ${{ secrets.REACT_APP_GOOGLE_STATIC_KEY }}
